### ISSUE TITLE
Alphabetizing issue

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#16]
Some discrepancy with the sorting. I assume it is the 'combined selectors', seeing as the alphabetizer has no issue with the my other class.

ORIGINAL CSS
```css
.contactForm input[type=submit] {
	min-height: 40px;
	display: block;
	margin: 0 auto;
	margin-top: 1%;
}
```

--SORT
```css
.contactForm input[type=submit]{
	display: block;
	min-height: 40px;
	margin: 0 auto;
	margin-top: 1%
}
```

ORIGINAL CSS
```css
.contactFullname, .contactEmail {
	margin: 0 auto;
	margin-bottom: 1%;
}
```

--SORT
```css
.contactFullname,
.contactEmail {
	margin-bottom: 1%;
	margin: 0 auto
}
```
