### ISSUE TITLE
Breaks calc()

### ISSUE THREAD

**Issue by Aeyoun** [juancarlospaco/css-html-js-minify#25]
At least one space is required around operators inside the `calc()` function.

Test:
```css
    .test { width: calc(  40% +   10px); height: calc(+800px +  -40% ); }
```
Expected minification:
```css
    .test{width:calc(40% + 10px);height:calc(800px + -40%)}
```
Current implementation returns the following (non-functional):
```css
    .test{width:calc(40%+10px);height:calc(+800px+-40%)}
```

**Comment by juancarlospaco** [comment]
Great, I was thinking something like that the other day but had no time to try it...

**Comment by juancarlospaco** [comment]
INPUT:
```css
 .test { width: calc(  40% +   10px); height: calc(+800px +  -40% ); }

 .test { width: calc(  40% -   10px); height: calc(+800px -  -40% ); }

 .test { width: calc(  40% *   10px); height: calc(+800px *  -40% ); }
```

OUTPUT:
```css
.test{width:calc(40% + 10px);height:calc(+800px + -40%)}
.test{width:calc(40% - 10px);height:calc(+800px - -40%)}
.test{width:calc(40% * 10px);height:calc(+800px * -40%)}
```
